# Generated by Django 4.0.6 on 2023-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_friendlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='body',
            field=models.TextField(default='uhj'),
        ),
    ]
