# Generated by Django 4.0.6 on 2023-02-03 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_friendroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendroom',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendroom',
            name='user',
        ),
        migrations.AddField(
            model_name='friendroom',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendroom',
            name='name',
            field=models.TextField(),
        ),
    ]
