# Generated by Django 4.0.6 on 2023-03-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_friendroom_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
